### ISSUE TITLE
大佬能给出个运行所需的环境么? 运行报错了

### ISSUE THREAD

**Issue by whcoding** [TurboWay/bigdata_practice#1]
### 不是很懂py 但是想用这个可视化工具 我安装了Python3, Flask
报错如下:  看样子应该是 SourceData 没有引入进来?
```
Traceback (most recent call last):
  File "app.py", line 14, in <module>
    from ironman.data import SourceData
ImportError: No module named ironman.data
```

**Comment by TurboWay** [comment]
> ### 不是很懂py 但是想用这个可视化工具 我安装了Python3, Flask
> 报错如下: 看样子应该是 SourceData 没有引入进来?
> 
> ```
> Traceback (most recent call last):
>   File "app.py", line 14, in <module>
>     from ironman.data import SourceData
> ImportError: No module named ironman.data
> ```

这应该是引用自定义包时的路径问题，app.py 开头有如下代码，就是用来解决这种问题的，不知道你是不是注释掉了。
```
import os
import sys

sys.path.append(os.path.dirname(os.path.abspath(__file__)) + '/../')
```

**Comment by whcoding** [comment]
> > ### 不是很懂py但是想用这个可视化工具我安装了Python3，Flask
> > 报错如下：看样子应该是SourceData没有约会进来？
> > ```
> > Traceback (most recent call last):
> >   File "app.py", line 14, in <module>
> >     from ironman.data import SourceData
> > ImportError: No module named ironman.data
> > ```
> 
> 这应该是引用自定义包时的路径问题，app.py开头有如下代码，就是使用解决这种问题的，不知道你是不是注释掉了。
> 
> ```
> import os
> import sys
> 
> sys.path.append(os.path.dirname(os.path.abspath(__file__)) + '/../')
> ```

可能是在虚拟机里运行的缘故,  在本地是没问题的 谢谢~
